Vagrant.configure("2") do |config|
    # Define a common base configuration for all VMs
    config.vm.box = "ubuntu/jammy64"  # Ubuntu 20.04
  
    # Define the master node
    config.vm.define "khadj-meS" do |master|
      master.vm.hostname = "khadj-meS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      master.vm.provision "shell", path: "./scripts/khadj-meS_setup.sh"
    end
end
