# app1 — Deployment
apiVersion: apps/v1
kind: Deployment
metadata: # just some metadata
  name: app1
spec:
  replicas: 1 # number of replicas
  selector: # see which pods are from this depl
    matchLabels:
      app: app1
  template: # new pods template
    metadata:
      labels:
        app: app1 # label for the pod
    spec:
      containers:
      - name: app1 # container name
        image: paulbouwer/hello-kubernetes:1.10 # docker image
        ports:
        - containerPort: 8080 # exposed port in the container
        env: # just some env
        - name: MESSAGE
          value: "Hello from APP1!"
---
# app1 — Service
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  selector:
    app: app1
  ports: # list of exposed ports
  - port: 80 # published port
    targetPort: 8080 # exposed port
---
# app2 — Deployment (3 replicas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from APP2!"
---
# app2 — Service
apiVersion: v1
kind: Service
metadata:
  name: app2-svc
spec:
  selector:
    app: app2
  ports:
  - port: 80
    targetPort: 8080
---
# app3 — Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from APP3!"
---
# app3 — Service
apiVersion: v1
kind: Service
metadata:
  name: app3-svc
spec:
  selector:
    app: app3
  ports:
  - port: 80
    targetPort: 8080
---
# Ingress — HOST routing rules
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: # just metadata
  name: apps-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web # get interest in this weird key/value
spec:
  # IT DOESNT WORKS K3S INGRESS OVERRIDES IT
  # defaultBackend: # default service -> default route
  #  service:
  #    name: app3-svc
  #  port:
  #      number: 80 # published port of the service
  rules: # route rules for http
  - host: app1.com # domaine
    http:
      paths:
      - path: / # route
        pathType: Prefix # match type
        backend: 
          service:
            name: app1-svc # service name
            port:
              number: 80 # service published port
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2-svc
            port:
              number: 80
  - host: _
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app3-svc
            port:
              number: 80

