 Vagrant.configure("2") do |config|

	config.vm.box = "debian/bookworm64"

	# VM 1
	config.vm.define "abalasubS" do |server|
		server.vm.network "private_network", ip: "192.168.56.111"
		server.vm.hostname = "abalasubS"
		server.vm.provider "virtualbox" do |vb|
			vb.name = "abalasubS" 
			vb.memory = 1024
			vb.cpus = 1
		end
		server.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get install -y curl
			curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip=192.168.56.111 --flannel-iface=eth1" sh -
		SHELL
	end
end