Vagrant.configure("2") do |config|
  # Debian LTS 12 (Bookworm) 64-bit
  config.vm.box = "debian/bookworm64"

  # VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

  MASTER_NODE_IP = "192.168.56.110"
  WORKER_IP = "192.168.56.111"

  # Kubernetes Master Node
  config.vm.define "k3s-master", primary: true do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: MASTER_NODE_IP
    master.vm.provision "shell", path: "./provisions/setup_k3s-master.sh", args: [MASTER_NODE_IP]
  end

  # Kubernetes Worker Node
  config.vm.define "k3s-worker" do |worker|
    worker.vm.hostname = "k3s-worker"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provision "shell", path: "./provisions/setup_k3s-worker.sh", args: [MASTER_NODE_IP]
  end

end
