Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # VM 1
  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.56.110"
    vm1.vm.hostname = "Server"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "Server" 
      vb.memory = 512
      vb.cpus = 1
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

  # VM 2
  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.56.111"
    vm2.vm.hostname = "ServerWorker"

    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ServerWorker"
      vb.memory = 512
      vb.cpus = 1
    end
    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

end