Vagrant.configure("2") do |config|
    # Define a common base configuration for all VMs
    config.vm.box = "debian/bookworm64"  # Latest debian ver
  
    # Define the master node
    config.vm.define "khadj-meS" do |master|
      master.vm.hostname = "khadj-meS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      master.vm.provision "shell", path: "./scripts/khadj-meS_setup.sh"
    end
  
    # Define the first worker node
    config.vm.define "khadj-meSW" do |worker1|
      worker1.vm.hostname = "khadj-meSW"
      worker1.vm.network "private_network", ip: "192.168.56.111"
      worker1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      worker1.vm.provision "shell", path: "./scripts/khadj-meSW_setup.sh", args: ["192.168.56.110"]
    end
end
